name: kinematic_formulae
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.2
  service_worker: ^0.2.3

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  sass_builder: ^2.1.3
  test: ^1.5.1

  quantaly_lints:
    git:
      url: https://github.com/quantaly/dart_lints
